print("hello world".rjust(20,"*"))
print ("hello world".ljust(20,"*"))
print ("hello world".center(20))
print ("hello world".center(21,"*"))
print ("hello world".lstrip("he"))
print ("hello world".rstrip("ld"))
print ("hello world".center(21,"*").strip("*"))
print ("hello world".replace("hello","bye"))